### PR TITLE
https://github.com/ComplianceAsCode/content/releases/tag/v0.1.65

### PR DESCRIPTION
**Pull request by jseiser**
https://github.com/ComplianceAsCode/content/releases/tag/v0.1.65

This has been released

### CODE REVIEW

**Comment by jseiser** [comment]
@dmc5179

**Comment by jseiser** [comment]
@RedHatDan
@redhatrises
@dmc5179 

I wanted to once again reach and and say if you all need assistance keeping this up to date, my team uses it and I would def. be willing to assist.

**Comment by jseiser** [comment]
@RedHatDan
@redhatrises
@dmc5179

Also this role in its current form fails to run under Ansible 7.  I think the lack of FQDN's and some legacy commands sed for `command` calls is the problem.

Id love to be able to open issues here.

**Comment by jseiser** [comment]
```
2022-12-19T20:58:08Z:     amazon-ebs.stig8: TASK [RedHatOfficial.rhel8_stig : Read signatures in GPG key] ******************
2022-12-19T20:58:09Z:     amazon-ebs.stig8: fatal: [default]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: stdin_add_newline, strip_empty_ends, stdin, argv, _uses_shell, _raw_params, chdir, executable, removes, creates."}
2022-12-19T20:58:09Z:     amazon-ebs.stig8:
```

**Comment by dmc5179** [comment]
@jseiser All of the ansible roles in the "RedHatOfficial" org are derived through automation from the main repo here: https://github.com/complianceascode/content

We don't merge any code changes here unless there is something that prevents the role from being syntactically valid. Any bugs or issues need to be filed in the upstream compliance as code repo.

**Comment by jseiser** [comment]
https://docs.ansible.com/ansible-core/2.14/collections/ansible/builtin/shell_module.html

Thats the problem, ansible core 2.14 removes that deprecated args.warn option

https://docs.ansible.com/ansible-core/2.13/collections/ansible/builtin/command_module.html#parameter-warn

**Comment by dmc5179** [comment]
> 

Where does this task appear in the RHEL 8 STIG playbook? I cannot find a task with a title "Read signatures in GPG key"
There also appears to be only a single task in the role that uses sed directly.
I also don't see any use of ansible.legacy which is only used when you want to override a built in module with your own.

**Comment by dmc5179** [comment]
Ah ok, I can see the "Read signatures in GPG key" tasks. My clone hadn't updated. I see that it uses the command module but I don't see anything about ansible.legacy. Perhaps that is automatically added in Ansible 7? I haven't tried it.

**Comment by jseiser** [comment]
> @jseiser All of the ansible roles in the "RedHatOfficial" org are derived through automation from the main repo here: https://github.com/complianceascode/content
> 
> We don't merge any code changes here unless there is something that prevents the role from being syntactically valid. Any bugs or issues need to be filed in the upstream compliance as code repo.

The role is not syntactically valid. Its using syntax that was removedd in ansible core 2.14.

```
- name: Read signatures in GPG key
  command: gpg --show-keys --with-fingerprint --with-colons "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
  args:
    warn: false
  changed_when: false
  register: gpg_fingerprints
  check_mode: false
  tags:
  - CCE-80795-8
  - CJIS-5.10.4.1
  - NIST-800-171-3.4.8
  - NIST-800-53-CM-5(3)
  - NIST-800-53-CM-6(a)
  - NIST-800-53-SC-12
  - NIST-800-53-SC-12(3)
  - NIST-800-53-SI-7
  - PCI-DSS-Req-6.2
  - ensure_redhat_gpgkey_installed
  - high_severity
  - medium_complexity
  - medium_disruption
  - no_reboot_needed
  - restrict_strategy
  when:
  - ensure_redhat_gpgkey_installed | bool
  - high_severity | bool
  - medium_complexity | bool
  - medium_disruption | bool
  - no_reboot_needed | bool
  - restrict_strategy | bool
  ```


If you searching via github search, it wont show because your task file is so large it doesnt search it.

as for builtin.command vs legacy.command, they are the same thing i believe

https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#what-is-the-difference-between-ansible-legacy-and-ansible-builtin-collections


The real issue is the args/warn stuff

https://docs.ansible.com/ansible-core/2.13/collections/ansible/builtin/command_module.html#parameter-warn

Got removed in 2.14

https://docs.ansible.com/ansible-core/2.14/collections/ansible/builtin/command_module.html

**Comment by dmc5179** [comment]
Since these roles are generated using a util in the compliance as code repo, an issue like that would need to be filed against the main compliance as code repo. I'm not sure they'll get to it right away:

- RHEL 8 is up to ansible core 2.13, which is what this role would be used on so it should run fine
- Fedora 37 is on ansible 6
- Fedora rawhide is on ansible 7

As far as I know the maintainers of the compliance as code repo are not trying to keep up with rawhide but this would be a good issue to submit to that repo and any updates to address it. This is the util that is used to transform the playbook into a role. You might try running the playbook directly and see if the error lies there or in the translation to a role:

https://github.com/ComplianceAsCode/content/blob/master/utils/ansible_playbook_to_role.py

**Comment by jseiser** [comment]
> Since these roles are generated using a util in the compliance as code repo, an issue like that would need to be filed against the main compliance as code repo. I'm not sure they'll get to it right away:
> 
>     * RHEL 8 is up to ansible core 2.13, which is what this role would be used on so it should run fine
> 
>     * Fedora 37 is on ansible 6
> 
>     * Fedora rawhide is on ansible 7
> 
> 
> As far as I know the maintainers of the compliance as code repo are not trying to keep up with rawhide but this would be a good issue to submit to that repo and any updates to address it. This is the util that is used to transform the playbook into a role. You might try running the playbook directly and see if the error lies there or in the translation to a role:
> 
> https://github.com/ComplianceAsCode/content/blob/master/utils/ansible_playbook_to_role.py

@dmc5179 

>     * RHEL 8 is up to ansible core 2.13, which is what this role would be used on so it should run fine

That doesnt make much sense honestly, im running this role AGAINST RHEL 8 servers, not FROM a rhel 8 server.  

But, thank you for your help, im moving all this over to the complianceascode repo.

Also, can we get 0.1.65 :)

**Comment by jseiser** [comment]
@dmc5179 

https://github.com/ComplianceAsCode/content/releases/tag/v0.1.66

**Comment by dmc5179** [comment]
@jseiser updated the roles to 1.66. Please let me know if they are not working or not showing up.

**Comment by jseiser** [comment]
@dmc5179 

Both show up on Ansible Galaxy, TY

**Comment by jseiser** [comment]
Can we please get this repo up to date with upstream? or is there another redhat official repo that is kept up to date?

Thanks

**Comment by dmc5179** [comment]
Submit issues and PRs here https://github.com/ComplianceAsCode/content

**Pull request closed without merging**
